version: '3.7'

services:
  app:
    image: chialab/php:7.2-apache
    working_dir: /app
    volumes:
      - ./:/app
      - ./virtualhost.conf:/etc/apache/sites-enabled/laravel.conf
    ports:
      - 127.0.0.1:8000:80
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hky
